<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Categoria;
use App\Models\Producto;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        $vinos = Categoria::where('slug', 'vinos')->first();
        $whiskys = Categoria::where('slug', 'whiskys')->first();
        $otros = Categoria::where('slug', 'otros')->first();

        $productos = [
            [
                'categoria_id' => $vinos->id,
                'nombre' => 'Obeja Black Reserva',
                'descripcion' => 'Notas a frutos rojos',
                'precio' => 15000,
                'stock' => 8,
                'url_imagen' => 'catalogoproductos/vino1.png',
                'origen' => 'Mendoza, Argentina',
                'bodega' => 'Oveja Black',
                'graduacion' => '13.5%',
                'volumen' => '750 ml',
                'variedad' => 'Malbec Reserva',
            ],
            [
                'categoria_id' => $vinos->id,
                'nombre' => 'Decoy Sonoma',
                'descripcion' => 'Intenso y elegante',
                'precio' => 60000,
                'stock' => 5,
                'url_imagen' => 'catalogoproductos/vino2.png',
                'origen' => 'Sonoma, Estados Unidos',
                'bodega' => 'Decoy',
                'graduacion' => '14.1%',
                'volumen' => '750 ml',
                'variedad' => 'Cabernet Sauvignon',
            ],
            [
                'categoria_id' => $vinos->id,
                'nombre' => 'Penfolds Bin 600 California',
                'descripcion' => 'Suave y equilibrado',
                'precio' => 150000,
                'stock' => 0,
                'url_imagen' => 'catalogoproductos/vino3.png',
                'origen' => 'California, Estados Unidos',
                'bodega' => 'Penfolds',
                'graduacion' => '14.5%',
                'volumen' => '750 ml',
                'variedad' => 'Blend tinto',
            ],
            [
                'categoria_id' => $vinos->id,
                'nombre' => 'El Enemigo',
                'descripcion' => 'Aromas especiados',
                'precio' => 21000,
                'stock' => 6,
                'url_imagen' => 'catalogoproductos/vino4.png',
                'origen' => 'Mendoza, Argentina',
                'bodega' => 'El Enemigo',
                'graduacion' => '13.9%',
                'volumen' => '750 ml',
                'variedad' => 'Malbec',
            ],
            [
                'categoria_id' => $vinos->id,
                'nombre' => 'Angélica Zapata',
                'descripcion' => 'Selección especial',
                'precio' => 29500,
                'stock' => 3,
                'url_imagen' => 'catalogoproductos/vino5.png',
                'origen' => 'Mendoza, Argentina',
                'bodega' => 'Catena Zapata',
                'graduacion' => '14%',
                'volumen' => '750 ml',
                'variedad' => 'Malbec Alta Gama',
            ],

            [
                'categoria_id' => $whiskys->id,
                'nombre' => 'Jack Daniels',
                'descripcion' => 'Whisky americano clásico',
                'precio' => 25000,
                'stock' => 7,
                'url_imagen' => 'catalogoproductos/whisky1.png',
                'origen' => 'Tennessee, Estados Unidos',
                'bodega' => 'Jack Daniel’s',
                'graduacion' => '40%',
                'volumen' => '750 ml',
                'variedad' => 'Tennessee Whiskey',
            ],
            [
                'categoria_id' => $whiskys->id,
                'nombre' => 'Johnnie Walker Black Label',
                'descripcion' => 'Intenso y elegante',
                'precio' => 35000,
                'stock' => 4,
                'url_imagen' => 'catalogoproductos/whisky2.png',
                'origen' => 'Escocia',
                'bodega' => 'Johnnie Walker',
                'graduacion' => '40%',
                'volumen' => '750 ml',
                'variedad' => 'Blended Scotch Whisky',
            ],
            [
                'categoria_id' => $whiskys->id,
                'nombre' => 'Johnnie Walker Blue Label',
                'descripcion' => 'Premium escocés',
                'precio' => 300000,
                'stock' => 2,
                'url_imagen' => 'catalogoproductos/whisky3.png',
                'origen' => 'Escocia',
                'bodega' => 'Johnnie Walker',
                'graduacion' => '40%',
                'volumen' => '750 ml',
                'variedad' => 'Blended Scotch Whisky Premium',
            ],
            [
                'categoria_id' => $whiskys->id,
                'nombre' => 'Chivas Regal',
                'descripcion' => 'Suave y distinguido',
                'precio' => 35000,
                'stock' => 0,
                'url_imagen' => 'catalogoproductos/whisky4.png',
                'origen' => 'Escocia',
                'bodega' => 'Chivas Regal',
                'graduacion' => '40%',
                'volumen' => '750 ml',
                'variedad' => 'Blended Scotch Whisky',
            ],
            [
                'categoria_id' => $whiskys->id,
                'nombre' => 'Jameson',
                'descripcion' => 'Irlandés equilibrado',
                'precio' => 30000,
                'stock' => 9,
                'url_imagen' => 'catalogoproductos/whisky5.png',
                'origen' => 'Irlanda',
                'bodega' => 'Jameson',
                'graduacion' => '40%',
                'volumen' => '750 ml',
                'variedad' => 'Irish Whiskey',
            ],

            [
                'categoria_id' => $otros->id,
                'nombre' => 'Athos Gin 500',
                'descripcion' => 'Ideal para cocktails',
                'precio' => 12000,
                'stock' => 6,
                'url_imagen' => 'catalogoproductos/otros1.png',
                'origen' => 'Argentina',
                'bodega' => 'Athos',
                'graduacion' => '40%',
                'volumen' => '500 ml',
                'variedad' => 'Gin',
            ],
            [
                'categoria_id' => $otros->id,
                'nombre' => 'Vodka',
                'descripcion' => 'Suave y versátil',
                'precio' => 10000,
                'stock' => 8,
                'url_imagen' => 'catalogoproductos/otros2.png',
                'origen' => 'Europa',
                'bodega' => 'Selección Viñas',
                'graduacion' => '37.5%',
                'volumen' => '750 ml',
                'variedad' => 'Vodka',
            ],
            [
                'categoria_id' => $otros->id,
                'nombre' => 'Ron Barceló',
                'descripcion' => 'Notas dulces',
                'precio' => 18000,
                'stock' => 4,
                'url_imagen' => 'catalogoproductos/otros3.png',
                'origen' => 'República Dominicana',
                'bodega' => 'Ron Barceló',
                'graduacion' => '37.5%',
                'volumen' => '750 ml',
                'variedad' => 'Ron',
            ],
            [
                'categoria_id' => $otros->id,
                'nombre' => 'Tequila 1800',
                'descripcion' => 'Intenso y auténtico',
                'precio' => 40000,
                'stock' => 0,
                'url_imagen' => 'catalogoproductos/otros4.png',
                'origen' => 'Jalisco, México',
                'bodega' => '1800 Tequila',
                'graduacion' => '40%',
                'volumen' => '750 ml',
                'variedad' => 'Tequila',
            ],
            [
                'categoria_id' => $otros->id,
                'nombre' => 'Vermouth Rosso',
                'descripcion' => 'Perfecto para compartir',
                'precio' => 15300,
                'stock' => 5,
                'url_imagen' => 'catalogoproductos/otros5.png',
                'origen' => 'Italia',
                'bodega' => 'Selección Rosso',
                'graduacion' => '15%',
                'volumen' => '750 ml',
                'variedad' => 'Vermouth',
            ],
        ];

        foreach ($productos as $producto) {
            Producto::create($producto);
        }
    }
}